language: scala
install:
  - pip install --user codecov

scala:
- 2.12.6

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coveralls